const $ = (id) => document.getElementById(id);
const input = $("imageInput"), run = $("runButton"), status = $("processingStatus");
let source = null, sourceName = "batik-artwork", activeTool = "enhance", result = { url: "", svg: "", blob: null };
const copy = { enhance:["AI UPSCALE","Prepare an 8K enhancement","Uses the secure server-side Replicate workflow. The highest practical scale is selected to target a 7,680px long edge when possible.","ENHANCE TO 8K","8K OUTPUT","Enhanced image"], outline:["LOCAL CONTOUR DRAWING","Create a Batik outline","Locally isolates textile contours into a clean black and white SVG stroke drawing. Your source image stays in this browser.","CREATE OUTLINE SVG","OUTLINE SVG","Batik outline"], vector:["LOCAL VECTOR TRACING","Create smooth vector artwork","Locally traces high-detail black and white Batik motifs into editable SVG paths. Your source image stays in this browser.","CREATE VECTOR ART","VECTOR SVG","Vector artwork"] };
function setStatus(message, kind="") { status.textContent=message; status.className=`status ${kind}`; }
function emptyResult() { result={url:"",svg:"",blob:null}; $("resultPreview").innerHTML="<p>Your completed artwork will appear here.</p>"; $("downloadPrimary").disabled=true; $("downloadSvg").disabled=true; }
function selectTool(tool) { activeTool=tool; document.querySelectorAll(".tool-card").forEach(b=>{const chosen=b.dataset.tool===tool;b.classList.toggle("active",chosen);b.setAttribute("aria-selected",chosen)}); const [kick,title,description,action,type,out]=copy[tool]; $("toolKicker").textContent=kick; $("toolTitle").textContent=title; $("toolDescription").textContent=description; $("outputType").textContent=type; $("outputTitle").textContent=out; $("traceControls").hidden=tool==="enhance"; run.textContent=source?action:"UPLOAD AN IMAGE FIRST"; run.disabled=!source; emptyResult(); setStatus(source?"Ready to process this image.":"Choose a tool, upload an image, and begin."); }
document.querySelectorAll(".tool-card").forEach(button=>button.addEventListener("click",()=>selectTool(button.dataset.tool)));
$("threshold").addEventListener("input",e=>$("thresholdOutput").textContent=e.target.value); $("detail").addEventListener("input",e=>$("detailOutput").textContent=e.target.value);
["dragover","dragenter"].forEach(type=>$("uploadZone").addEventListener(type,e=>{e.preventDefault();$("uploadZone").classList.add("dragging")}));["dragleave","drop"].forEach(type=>$("uploadZone").addEventListener(type,e=>{e.preventDefault();$("uploadZone").classList.remove("dragging")}));$("uploadZone").addEventListener("drop",e=>loadFile(e.dataTransfer.files[0]));input.addEventListener("change",()=>loadFile(input.files[0]));
function loadFile(file) { if(!file)return; if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>15*1024*1024){setStatus("Use a JPG, PNG, or WebP image no larger than 15 MB.","error");return} const reader=new FileReader();reader.onload=e=>{const image=new Image();image.onload=()=>{source=image;sourceName=file.name.replace(/\.[^.]+$/,"")||"batik-artwork";$("originalPreview").replaceChildren(image);$("fileMeta").textContent=`${file.name} · ${(file.size/1024/1024).toFixed(1)} MB`;run.disabled=false;run.textContent=copy[activeTool][3];emptyResult();setStatus("Image loaded. Ready when you are.","success")};image.onerror=()=>setStatus("This image could not be opened.","error");image.src=e.target.result};reader.readAsDataURL(file) }
run.addEventListener("click",async()=>{if(!source)return;run.disabled=true; const original=run.textContent; try{if(activeTool==="enhance")await enhance();else trace(activeTool);run.textContent=original}catch(error){console.error(error);setStatus(error.message||"Processing failed. Please try another image.","error")}finally{run.disabled=false}});
async function enhance(){const longest=Math.max(source.naturalWidth,source.naturalHeight);const scale=longest<3840?4:2;setStatus(`Sending image securely for AI enhancement (up to ${scale}×).`,"");const image=toDataUrl(source,Math.min(2200,Math.max(source.naturalWidth,source.naturalHeight)));const response=await fetch("/api/enhance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({image,scale})});const payload=await response.json().catch(()=>({}));if(!response.ok||!payload.output)throw new Error(payload.error||"The enhancement service did not return an image.");const url=Array.isArray(payload.output)?payload.output[0]:payload.output;if(typeof url!=="string")throw new Error("The enhancement service returned an invalid image.");result.url=url;const imageNode=new Image();imageNode.crossOrigin="anonymous";imageNode.onload=()=>$("resultPreview").replaceChildren(imageNode);imageNode.onerror=()=>setStatus("Enhanced image is ready, but its preview could not load. Download is still available.","error");imageNode.src=url;$("downloadPrimary").disabled=false;setStatus("8K enhancement completed successfully.","success")}
function toDataUrl(image,max){const ratio=Math.min(1,max/Math.max(image.naturalWidth,image.naturalHeight));const canvas=document.createElement("canvas");canvas.width=Math.round(image.naturalWidth*ratio);canvas.height=Math.round(image.naturalHeight*ratio);canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);return canvas.toDataURL("image/png")}
function trace(mode){if(typeof ImageTracer==="undefined")throw new Error("The vector engine is still loading. Please try again shortly.");setStatus(mode==="outline"?"Finding and tracing Batik contours…":"Cleaning and tracing Batik motifs…");setTimeout(()=>{try{const detail=Number($("detail").value),threshold=Number($("threshold").value),canvas=document.createElement("canvas"),max=mode==="vector"?2200:1800,ratio=Math.min(1,max/Math.max(source.naturalWidth,source.naturalHeight));canvas.width=Math.round(source.naturalWidth*ratio);canvas.height=Math.round(source.naturalHeight*ratio);const ctx=canvas.getContext("2d",{willReadFrequently:true});ctx.drawImage(source,0,0,canvas.width,canvas.height);const data=ctx.getImageData(0,0,canvas.width,canvas.height);makeMonochrome(data,threshold,mode==="outline",$("invert").checked);const options={numberofcolors:2,colorsampling:0,colorquantcycles:1,ltres:Math.max(.3,2.1-detail*.18),qtres:Math.max(.3,2.1-detail*.18),pathomit:detail>7?1:2,rightangleenhance:false,linefilter:false,scale:1,viewbox:true,desc:false};result.svg=ImageTracer.imagedataToSVG(data,options);const container=$("resultPreview");container.innerHTML=result.svg;const svg=container.querySelector("svg");svg.setAttribute("preserveAspectRatio","xMidYMid meet");if(mode==="outline"){svg.querySelectorAll("path").forEach(path=>path.setAttribute("stroke-linejoin","round"));}$("downloadPrimary").disabled=false;$("downloadSvg").disabled=false;setStatus(mode==="outline"?"Batik outline SVG created.":"Smooth Batik vector created.","success")}catch(error){setStatus(error.message||"Tracing failed.","error")}finally{run.disabled=false}},30)}
function makeMonochrome(imageData,threshold,edges,invert){const d=imageData.data,w=imageData.width,h=imageData.height,gray=new Uint8ClampedArray(w*h);for(let i=0,p=0;i<d.length;i+=4,p++)gray[p]=.299*d[i]+.587*d[i+1]+.114*d[i+2];for(let y=0;y<h;y++)for(let x=0;x<w;x++){const p=y*w+x;let value;if(edges&&x>0&&y>0&&x<w-1&&y<h-1){const gx=gray[p+1]-gray[p-1],gy=gray[p+w]-gray[p-w];value=Math.hypot(gx,gy)>Math.max(18,(255-threshold)/3)?0:255}else value=gray[p]>=threshold?255:0;if(invert)value=255-value;d[p*4]=d[p*4+1]=d[p*4+2]=value;d[p*4+3]=255}}
function download(blob,name){const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
$("downloadPrimary").addEventListener("click",async()=>{if(result.url){try{const response=await fetch(result.url);if(!response.ok)throw new Error("download response failed");download(await response.blob(),`${sourceName}-8k.png`)}catch{const link=document.createElement("a");link.href=result.url;link.target="_blank";link.rel="noopener";link.click();setStatus("Opened the enhanced image for download.","success")}}else if(result.svg)download(new Blob([result.svg],{type:"image/svg+xml"}),`${sourceName}-${activeTool}.svg`)});$("downloadSvg").addEventListener("click",()=>result.svg&&download(new Blob([result.svg],{type:"image/svg+xml"}),`${sourceName}-${activeTool}.svg`));$("resetButton").addEventListener("click",()=>{input.value="";source=null;$("originalPreview").innerHTML="<p>Upload an image to preview it here.</p>";$("fileMeta").textContent="No image selected. Local vector and outline processing stays in your browser.";selectTool(activeTool)});window.addEventListener("load",()=>{$("engineStatus").innerHTML=typeof ImageTracer==="undefined"?"<i></i> VECTOR ENGINE UNAVAILABLE":"<i></i> VECTOR ENGINE READY"});selectTool("enhance");
